### ISSUE TITLE
Router breaks setting paths with multiple leaf keys.

### ISSUE THREAD

**Issue by trxcllnt** [Netflix/falcor-router#144]
Copied from https://github.com/Netflix/falcor/issues/576:

>
@michaelbpaulson the matcher ([operations/matcher/index.js](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js)) [distributes](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L43) collapsed PathSets into distinct (simple) matches, but when all the matches [collapse back](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L75) into a single PathSet, only the [first match](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L93) is pushed into the `collapsedMatched` list. The `reducedMatch` list has a match for each leaf in the original PathSet, but `collapsedResults` only has one element, since all the matches came from the same PathSet and can be re-collapsed into one Path.
>
I reproduced this with the following code in node:
```js
var falcor = require("falcor");
var Router = require("falcor-router");
var inspect = require("util").inspect;
>
falcor({source: new Router([{
    route: ['path', 'to', ['a', 'b', 'c']],
    set: function(jsonGraph) {
        console.log('set route args:', inspect(arguments, {depth: null}));
        return {
            paths: [['path', 'to', ['a', 'b', 'c']]],
            jsonGraph: jsonGraph
        };
    }
}])}).set({json: { path: { to: {
    a: "aaa",
    b: "bbb",
    c: "ccc",
}}}}).subscribe(function(data) {
    console.log('result:', inspect(data, {depth: null}));
});
```

**Comment by ekosz** [comment]
I just came across this today. I thought I was going mad thinking it was an issue with my code. Is there anything I can do to help fix this bug?

**Comment by trxcllnt** [comment]
@ekosz we can try lobbying @michaelbpaulson or @sdesai to investigate further, though I believe Michael's still on leave.

**Comment by trxcllnt** [comment]
also @jhusain

**Comment by sdesai** [comment]
I can try and free up some time to look at this tomorrow.

**Comment by ekosz** [comment]
Just pinging this issue again. I believe this is a major gotcha right now. It would be nice to be able to use an official release again rather than work off of a fork where this is fixed.

Thanks!

**Comment by sdesai** [comment]
Hey @ekosz - Sorry, this fell through the cracks. my bad. @michaelbpaulson is on an issue resolution bender right now, I've asked if he could free up some cycles to look into it.

**Comment by michaelbpaulson** [comment]
@ekosz I am off of the leaves and unto the falcor.  I'll take a look at this and see if I can get a fix into master.
