### ISSUE TITLE
Should Router fail parse step because of whitespace?

### ISSUE THREAD

**Issue by gfogle** [Netflix/falcor-router#148]
When defining routes, I don't see where the docs explicitly state this, but it appears that the router fails when it encounters whitespace in definitions.

For instance, this definition was failing for me:

<img width="525" alt="screen shot 2015-11-15 at 7 43 44 pm" src="https://cloud.githubusercontent.com/assets/7015773/11172222/731d245c-8bd1-11e5-8c3b-9d961d4582a5.png">

And giving me this error:

<img width="575" alt="screen shot 2015-11-15 at 7 45 56 pm" src="https://cloud.githubusercontent.com/assets/7015773/11172227/8b5bca50-8bd1-11e5-8b5a-fe93fe395ecb.png">

But when I changed the definition to:

<img width="517" alt="screen shot 2015-11-15 at 7 43 31 pm" src="https://cloud.githubusercontent.com/assets/7015773/11172232/95f8d278-8bd1-11e5-91f1-b4716f2f7b92.png">

Everything appeared to be fine. Is this strict definition expected and/or desired behavior? If not, happy to submit a PR to enhance the parser.

**Comment by michaelbpaulson** [comment]
It really should not fail due to white space.  That is something I can take care of at some point.  I'll be doing some string syntax work this week, more than likely, and could get this fix in.
