### ISSUE TITLE
Refs to leaf nodes don't work

### ISSUE THREAD

**Issue by greim** [Netflix/falcor-router#175]
My route pattern for follow status is:

```js
"users[{keys}].is_following_user[{keys}]"
```

...which returns `true` or `false`. But I also want a convenience route:

```js
"users[{keys}].is_followed_by_me"
```

...which would use session context to determine the logged-in user's id and return a ref, like:

```
{ $type: 'ref', value: ['users', <loggedInId>, 'is_following_user', <otherId>] }
```

But the router doesn't follow the ref. In other words, I expected the response:

```
/api/model.json?paths=[[%22users%22,1,%22is_followed_by_me%22]]&method=get
<= {
  "jsonGraph": {
    "users": {
      "1": {
        "is_followed_by_me": {
          "$type": "ref",
          "value": [ "users", 4, "is_following_user", 1 ]
        }
      },
      "4": {
        "is_following_user": {
          "1": true
        }
      }
    }
  }
}
```

...but the actual response was:

```
/api/model.json?paths=[[%22users%22,1,%22is_followed_by_me%22]]&method=get
<= {
  "jsonGraph": {
    "users": {
      "1": {
        "is_followed_by_me": {
          "$type": "ref",
          "value": [ "users", 4, "is_following_user", 1 ]
        }
      }
    }
  }
}
```

Does the router not allow refs to leaf nodes?

**Comment by trxcllnt** [comment]
@greim can you try putting `null` at the end of your path? context: https://github.com/Netflix/falcor/issues/620#issuecomment-157093682

**Comment by greim** [comment]
That worked strangely enough. I'll close this since it's a dupe.
